# Generated by Django 2.1.7 on 2019-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='password',
            field=models.CharField(default='010', max_length=24, verbose_name='Password'),
        ),
    ]
