# Generated by Django 2.1.7 on 2019-04-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190410_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mainapp.ChatRoom', verbose_name='ChatRoom'),
        ),
    ]
