# Generated by Django 2.1.7 on 2019-04-10 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_message_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 13, 59, 41, 200135), verbose_name='Date'),
        ),
    ]
