# Generated by Django 2.1.7 on 2019-04-10 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 14, 13, 11, 222213), verbose_name='Date'),
        ),
    ]
