# Generated by Django 2.1.7 on 2019-04-10 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190410_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatRoom',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 14, 13, 43, 351359), verbose_name='Date'),
        ),
    ]
