# Generated by Django 2.1.7 on 2019-04-10 11:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190410_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mainapp.ChatRoom', verbose_name='ChatRoom'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 14, 14, 2, 532301), verbose_name='Date'),
        ),
    ]
